Allow for specifying kubeconfigName in the config file
danielfoehrKn/kubeswitch pull request #9
Opened 2021-03-03 10:04 UTC by herbygillot

2021-03-03 10:08 UTC, danielfoehrKn commented
Thanks, I ll try to take a look at it today!

2021-03-03 20:39 UTC, danielfoehrKn requested changes
Besides a nit I tested it and it works. Thanks!

I already had in mind to make this configurable per path, but this is also great as a global default.

2021-03-03 20:39 UTC, danielfoehrKn commented on cmd/switcher/switcher.go
> +const defaultKubeconfigName = "config"
```suggestion
const (
	vaultTokenFileName = ".vault-token"
	defaultKubeconfigName = "config"
)
```

2021-03-03 22:15 UTC, herbygillot commented
> Besides a nit I tested it and it works. Thanks!
> 
> I already had in mind to make this configurable per path, but this is also great as a global default.

Resolved. I 100% agree with you that this should also be available per-path, but `kubeswitch` definitely needed this as a core config option just to start.

2021-03-04 08:03 UTC, danielfoehrKn approved these changes

2021-03-04 08:04 UTC, merged

2021-03-04 08:50 UTC, herbygillot commented
BTW @danielfoehrKn, can we cut a minor release with this functionality?  Maybe an 0.3.1...? Thanks.

2021-03-04 08:53 UTC, danielfoehrKn commented
Sure, will create a patch release with `0.3.1 `

2021-03-04 09:00 UTC, danielfoehrKn commented
Release[ job was successful](https://github.com/danielfoehrKn/kubeswitch/actions/runs/620423047) and the release is available via homebrew.

2021-03-04 09:20 UTC, herbygillot commented
Excellent, thank you.  The [port has been updated](https://github.com/macports/macports-ports/commit/3e1210d2da57478311406006c593985aa95c9c20), so this release will also be available in MacPorts shortly as well.